# vim:sw=2:ts=2
name: ci

# on events
on:
  workflow_dispatch:
  push:
    branches:
      - runner-poc

# jobs
jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ['armv7m7-imxrt106x']
        include:
          - target: 'ia32-generic'
            syspage: 'psh pc-ata uart16550'
    steps:
      # step 1: checkout repository code inside the workspace directory of the runner
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # attach GCC problem matcher... might not work because of submodules... just trying
      - uses: ammaraskar/gcc-problem-matcher@master

      # step 2: use our custom action to build the project
      - name: Build
        uses: ./.github/actions/phoenix-build
        with:
          target: ${{ matrix.target }}
          syspage: ${{ matrix.syspage }}
          param1: 'clean'
          param2: 'core'
          param3: 'fs'
          param4: 'test'
          param5: 'project'
          param6: 'image'

      # step 3: upload contents of "_boot" as build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: phoenix-rtos-${{ matrix.target }}
          path: _boot

          #test:
          #  needs: build
          #  name: run tests
          #  runs-on: ubuntu-latest
          #  strategy:
          #    matrix:
          #      target: ['host-pc', 'ia32-generic']

          #  steps:
          #    - name: Checkout the repository
          #      uses: actions/checkout@v2
          #      with:
          #        submodules: true

          #    - name: Download build artifacts
          #      uses: actions/download-artifact@v2
          #      with:
          #        name: phoenix-rtos-${{ matrix.target }}
          #        path: _boot

          #    - name: Fix file permissions
          #      if: ${{ matrix.target == 'host-pc' }}
          #      run: find _boot/host-pc/ -type f -exec chmod 755 {} \;

          #    - name: Test runner
          #      uses: ./.github/actions/phoenix-runner
          #      with:
          #        target: ${{ matrix.target }}

  test-hw:
    needs: build
    name: Run tests on hardware
    runs-on: [self-hosted]
    strategy:
      matrix:
        target: ['armv7m7-imxrt106x']

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: phoenix-rtos-${{ matrix.target }}
          path: _boot

      - name: Test runner
        run: |
          python3 ./phoenix-rtos-tests/runner.py -T${{ matrix.target }}

